[build]
  # Build from the frontend folder
  base    = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/build"

# Redirect all paths (including form POSTs) to index.html so your SPA never 404s
[[redirects]]
  from     = "/*"
  to       = "/index.html"
  status   = 200
  force    = true




