[build]
  # Tell Netlify to run inside the frontend folder
  base = "frontend"
  # How to build
  command = "npm install && npm run build"
  # What to publish (relative to repo root)
  publish = "frontend/build"


